name: Mautic
description: |
  Powerful marketing automation.
version: v2.12
category: Marketing Automation
maintainer: "Kohsaku Saito <kohsaku.saito@leap-arrows.jp>"
projectURL: https://github.com/KohsakuSaito/rancher-mautic.git 
