name: Mautic
description: |
  Powerful marketing automation.
version: 2.12.0
category: Marketiing Automation
maintainer: "Kohsaku Saito <kohsaku.saito@leap-arrows.jp>"
projectURL: https://github.com/KohsakuSaito/rancher-mautic.git 
