version: '2'
services:
  mautic:
    image: mautic/mautic:${mautic_version}
    environment:
      MAUTIC_DB_HOST: ${mautic_db_host}
      MAUTIC_DB_NAME: ${mautic_db_name}
      MAUTIC_DB_USER: ${mautic_db_user}
      MAUTIC_DB_PASSWORD: ${mautic_db_password}
    volumes:
      - mautic-data:/var/www/html
    links:
      - mautic-db:mysql
    labels:
        io.rancher.container.hostname_override: container_name

  mautic-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${mautic_db_password}
    volumes:
      - mautic-db:/var/lib/mysql
    labels:
      io.rancher.container.hostname_override: container_name

  mautic-lb:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
      - ${public_port}:80/tcp
    links:
      - mautic-lb:mautic
    labels:
      io.rancher.container.hostname_override: container_name


volumes:
    mautic-data:
    mautic-db:
