.catalog:
  name: "Mautic"
  version: "v2.12"
  description: "Mautic provides free and open source marketing automation software available to everyone. Free email marketing software, lead management software and more."
  uuid: Mautic-0
  minimum_rancher_version: v0.51.0
  questions:

    - variable: mautic_version
      description: "Mautic version/Docker tag used for the Mautic container images."
      label: "MAUTIC_VERSION"
      type: enum
      default: "latest"
      options:
        - latest
        - apache
        - 2.12-apache
        - 2.11-apache
        - 2.10-apache
        - 2.9-apache
        - 2.8-apache

    - variable: public_port
      description: "public port to access the mautic site"
      label: "PUBLIC_PORT"
      required: true
      default: "80"
      type: "int"

    - variable: mautic_db_host
      description: "mautic database host"
      label: "MAUTIC_DB_HOST"
      required: true
      default: "mysql"
      type: "string"

    - variable: mautic_db_name
      description: "mautic database name"
      label: "MAUTIC_DB_NAME"
      required: true
      default: "mautic"
      type: "string"

    - variable: mautic_db_user
      description: "mautic user name"
      label: "MAUTIC_DB_USER"
      required: true
      default: "root"
      type: "string"

    - variable: mautic_db_password
      description: "mautic db password"
      label: "MYSQL_ROOT_PASSWORD"
      required: true
      type: "password"

services:

  mautic-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: mautic
        source_port: ${public_port}
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      strategy: recreate

  mautic:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 80
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
      request_line: GET / HTTP/1.0